server:
  port: 8080
  # 下面这个参数是为解决问题而新增的
  tomcat:
    max-http-header-size: 8192

mybatis:
  mapper-locations: classpath:mapper/*.xml

hikari:
  max-idle: 10 #指定连接池最大的空闲连接数量.
  max-wait: 10000 #指定连接池等待连接返回的最大等待时间，毫秒单位.
  min-idle: 5 #指定必须保持连接的最小值(For DBCP and Tomcat connection pools)
  initial-size: 5 #指定启动连接池时，初始建立的连接数量
  validation-query: SELECT 1 #指定获取连接时连接校验的sql查询语句.
  test-on-borrow: false #获取连接时候验证，会影响性能
  test-while-idle: true #当连接空闲时，是否执行连接测试.
  time-between-eviction-runs-millis: 18800 #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔


